title: MVS+ Beta
description: <script src="https://cdn.jsdelivr.net/gh/leonardosnt/mc-player-counter/dist/mc-player-counter.min.js"></script> Online - **<span data-playercounter-ip="mc.hypixel.net">0</span>**
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
